# Generated by Django 3.2.13 on 2022-05-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('app_name', models.CharField(max_length=25, verbose_name='app_name')),
            ],
        ),
    ]
